//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int USER_ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string USER_NAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string TELEPHONE { get; set; }
    }
}
